// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace LibraryBackend.Models
{
    public partial class OrderStatus
    {
        public int Id { get; set; }
        public string Status { get; set; }
    }
}